name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
            java-version: '11'
            distribution: 'temurin'
            architecture: x64
            
      - name: run the doe and test the code
        run: |
              cd src
              javac add.java
              java add
